# Generated by Django 3.2.4 on 2021-06-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('pk_cargo', models.AutoField(primary_key=True, serialize=False, verbose_name='pkCargo')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('salario', models.FloatField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('pk_endereco', models.AutoField(primary_key=True, serialize=False, verbose_name='IdEndereco')),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pk_pessoa', models.AutoField(primary_key=True, serialize=False, verbose_name='pkPessoa')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(verbose_name='dataNascimento')),
                ('telefone', models.CharField(max_length=14)),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Administrador da Instituição'), (2, 'Administrador do Sistema'), (3, 'Agente de Saúde'), (4, 'Agente de Secretaria')])),
                ('fk_endereco', models.ForeignKey(db_column='pk_endereco', on_delete=django.db.models.deletion.PROTECT, to='pessoa.endereco', verbose_name='fkEndereco')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='DadosProfissional',
            fields=[
                ('pk_dados_profissional', models.AutoField(primary_key=True, serialize=False, verbose_name='pkDadosProfissionais')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('pis_pasep', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('ctps', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_cargo', models.ForeignKey(db_column='pk_cargo', on_delete=django.db.models.deletion.PROTECT, to='pessoa.cargo', verbose_name='fkCargo')),
            ],
            options={
                'verbose_name': 'DadosProfissional',
                'verbose_name_plural': 'DadosProfissionais',
                'db_table': 'dados_profissional',
            },
        ),
        migrations.CreateModel(
            name='AgenteSecretaria',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('pk_agente_secretaria', models.AutoField(primary_key=True, serialize=False, verbose_name='pk_agente_secretaria')),
                ('fk_dados_profissional', models.ForeignKey(db_column='pk_dados_profissional', on_delete=django.db.models.deletion.PROTECT, to='pessoa.dadosprofissional', verbose_name='fkDadosProfissional')),
            ],
            options={
                'verbose_name': 'AgenteSecretaria',
                'verbose_name_plural': 'AgenteSecretarias',
                'db_table': 'agente_secretaria',
            },
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='AdministradorSistema',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('pk_adm_sistema', models.AutoField(primary_key=True, serialize=False, verbose_name='pk_adm_sistema')),
                ('fk_dados_profissional', models.ForeignKey(db_column='pk_dados_profissional', on_delete=django.db.models.deletion.PROTECT, to='pessoa.dadosprofissional', verbose_name='fkDadosProfissional')),
            ],
            options={
                'verbose_name': 'AdministradorSistema',
                'verbose_name_plural': 'AdministradorSistemas',
                'db_table': 'administrador_sistema',
            },
            bases=('pessoa.pessoa',),
        ),
    ]
