# Generated by Django 3.2.4 on 2021-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissao',
            name='data_nascimento',
            field=models.DateField(verbose_name='data Nascimento'),
        ),
    ]
