# Generated by Django 3.2.4 on 2021-06-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissao',
            name='upload',
        ),
        migrations.AlterField(
            model_name='profissao',
            name='fotoPerfil',
            field=models.FileField(blank=True, null=True, upload_to='static/fotos/', verbose_name='Foto do Perfil'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='tipo_usuario',
            field=models.CharField(max_length=40, verbose_name='Tipo de Usuario'),
        ),
    ]
